require "options"
require "keymaps"
require "plugins"
require "git"
require "terminal"

require "ui/colorscheme"
require "ui/statusline"
require "ui/indent-blankline-config"

require "navigation/nvimtree"
require "navigation/bufferlinenvim"
require "navigation/telescope-config"

require "lsp/treesitter"
require "lsp/lsp-config"
require "lsp/mason-config"
require "lsp/null-ls-config"
require "lsp/auto-cmp"
require "lsp/dap-config"
